package com.web.divyadrushti.models;
// Generated Feb 22, 2016 5:57:07 AM by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name="users")
@JsonIgnoreProperties({"devices"})
public class User  implements java.io.Serializable {

    /**
    * 
    */
    private static final long serialVersionUID = 1L;
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column
    private int id;

    private String name;
    private String email;
    private String mobileNumber;
    private String billingAddress;
    private String shippingAddress;
    private String loginPassword;
    private String devicePassword;
    private int active;
    
    @Column
    @Temporal(TemporalType.DATE)
    private Date whenCreated;
    
    @Column
    @Temporal(TemporalType.DATE)
    private Date whenUpdated;
    private String tmpRoleForAuth;
    private Integer whyNotActiveId;
    
    @JsonIgnore(true)
    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "userId")
    @OrderBy("id DESC")
    private List<Device> devices = new ArrayList<>();

    public User() {
    }

	
    public User(String name, String email, String loginPassword, int active, Date whenCreated, Date whenUpdated, String tmpRoleForAuth) {
        this.name = name;
        this.email = email;
        this.loginPassword = loginPassword;
        this.active = active;
        this.whenCreated = whenCreated;
        this.whenUpdated = whenUpdated;
        this.tmpRoleForAuth = tmpRoleForAuth;
    }
    public User(String name, String email, String mobileNumber, String billingAddress, String shippingAddress, String loginPassword, String devicePassword, int active, Date whenCreated, Date whenUpdated, String tmpRoleForAuth, Integer whyNotActiveId) {
       this.name = name;
       this.email = email;
       this.mobileNumber = mobileNumber;
       this.billingAddress = billingAddress;
       this.shippingAddress = shippingAddress;
       this.loginPassword = loginPassword;
       this.devicePassword = devicePassword;
       this.active = active;
       this.whenCreated = whenCreated;
       this.whenUpdated = whenUpdated;
       this.tmpRoleForAuth = tmpRoleForAuth;
       this.whyNotActiveId = whyNotActiveId;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getMobileNumber() {
        return this.mobileNumber;
    }
    
    public void setMobileNumber(String mobileNumber) {
        this.mobileNumber = mobileNumber;
    }
    public String getBillingAddress() {
        return this.billingAddress;
    }
    
    public void setBillingAddress(String billingAddress) {
        this.billingAddress = billingAddress;
    }
    public String getShippingAddress() {
        return this.shippingAddress;
    }
    
    public void setShippingAddress(String shippingAddress) {
        this.shippingAddress = shippingAddress;
    }
    public String getLoginPassword() {
        return this.loginPassword;
    }
    
    public void setLoginPassword(String loginPassword) {
        this.loginPassword = loginPassword;
    }
    public String getDevicePassword() {
        return this.devicePassword;
    }
    
    public void setDevicePassword(String devicePassword) {
        this.devicePassword = devicePassword;
    }
    public int getActive() {
        return this.active;
    }
    
    public void setActive(int active) {
        this.active = active;
    }
    public Date getWhenCreated() {
        return this.whenCreated;
    }
    
    public void setWhenCreated(Date whenCreated) {
        this.whenCreated = whenCreated;
    }
    public Date getWhenUpdated() {
        return this.whenUpdated;
    }
    
    public void setWhenUpdated(Date whenUpdated) {
        this.whenUpdated = whenUpdated;
    }
    public String getTmpRoleForAuth() {
        return this.tmpRoleForAuth;
    }
    
    public void setTmpRoleForAuth(String tmpRoleForAuth) {
        this.tmpRoleForAuth = tmpRoleForAuth;
    }
    public Integer getWhyNotActiveId() {
        return this.whyNotActiveId;
    }
    
    public void setWhyNotActiveId(Integer whyNotActiveId) {
        this.whyNotActiveId = whyNotActiveId;
    }
    
    public List<Device> getDevices(){
        return this.devices;
    }
    
    public void setDevices(List<Device> devices){
        this.devices = devices;
    }




}


