package com.web.divyadrushti.models;
// Generated Feb 22, 2016 5:57:07 AM by Hibernate Tools 4.3.1

/**
 * User generated by hbm2java
 */
public class UserRole  implements java.io.Serializable {


     private Integer id;
     private String email;
     private String role;

    public UserRole(String email, String role) {

       this.email = email;
       this.role = role;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }

}


